### ISSUE TITLE
Deploy on local node

### ISSUE THREAD

**Issue by SyedImam1998** [Synthetixio/staking#1191]
Hi team,
Could you please help me, how can I deploy this dapp on my local node, I have tried it but it is only working on mainnet and kovan. Could you please help me here?
I just wanted to learn how synthetix dapp work.....

**Comment by SyedImam1998** [comment]
i have add local here
`const networks = ['kovan', 'kovan-ovm', 'mainnet', 'mainnet-ovm', 'local'];` 
in next.config.js file

but i am getting this error
`Error: Cannot find module 'synthetix/publish/deployed/local/deployment.json'
Require stack:
- C:\Users\ACER\Desktop\staking-dev\scripts\minify-synthetix-contract.js
- C:\Users\ACER\Desktop\staking-dev\next.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (C:\Users\ACER\Desktop\staking-dev\node_modules\next\dist\build\webpack\require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\ACER\Desktop\staking-dev\scripts\minify-synthetix-contract.js:6:22
    at Array.forEach (<anonymous>)
    at generate (C:\Users\ACER\Desktop\staking-dev\scripts\minify-synthetix-contract.js:5:11)
    at optimiseContracts (C:\Users\ACER\Desktop\staking-dev\next.config.js:12:2)
    at Object.webpack (C:\Users\ACER\Desktop\staking-dev\next.config.js:41:4) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\ACER\\Desktop\\staking-dev\\scripts\\minify-synthetix-contract.js',
    'C:\\Users\\ACER\\Desktop\\staking-dev\\next.config.js'
  ]
}`

can you please guide what else can i do here.?

**Comment by SyedImam1998** [comment]
Dapp is requesting me to change to mainnet. it is not working with ganache.
![image](https://user-images.githubusercontent.com/52135949/180998096-7b0eb1ce-de2b-40d7-9a9d-0940cba61ce5.png)

**Comment by SyedImam1998** [comment]
getting faucet for them is lot difficult that is the reason why i trying to deploy it on local ....
